source: src
default_build: release
update_source: nosial/federationlib@n64
repository:
  name: n64
  type: github
  host: git.n64.cc
  ssl: true
assembly:
  name: BayesianPlugin
  package: net.nosial.bayesian_plugin
  version: 1.0.0
dependencies:
  net.nosial.federation: nosial/federationlib:dev@github
build_configurations:
  -
    name: debug
    output: 'target/debug/${ASSEMBLY.PACKAGE}.ncc'
    type: ncc
    definitions:
      NCC_DEBUG: true
    options:
      federationlib: &federationlib
        event_handlers:
          # Classifies the content of every content scan with BayesianServer
          -
            event: CONTENT_SCAN
            class: \BayesianPlugin\EventHandlers\ContentScanHandler::class
          # Trains BayesianServer with the text content of classified evidence
          -
            event: RECORD_CHANGE
            class: \BayesianPlugin\EventHandlers\EvidenceClassifiedHandler::class
            filter: EVIDENCE_CLASSIFIED
  -
    name: release
    output: 'target/release/${ASSEMBLY.PACKAGE}.ncc'
    type: ncc
    options:
      federationlib: *federationlib
